microsoft/FluidHelloWorld

package-lock.json
package.json

pulling in #46 #45 #43 #42 #40

bump fluid and webpack deps

---

package-lock.json
package.json

fixes #58 
fixes #57 
fixes #55

update all fluid packags

---

src/app.ts
src/kvpair-dataobject/FluidStatic.ts

createDocument -> createContainer

Document -> Container

---

package-lock.json
package.json
src/app.ts

fixes #119
fixes #118
fixes #117
fixes #111
fixes #74

bumping fluid and moving to get-container

---

package-lock.json
package.json

Bump the packages to version 0.48 for public preview

0.48 version bump

---

src/app.js

the attach needs to be awaited to get the id. I'm not really sure how this works at all.

await container.attach()

---

package-lock.json
package.json

Updates the `start:server` script and the package-lock based off of just running `npm i` since it looks like that hadn't been updated in a while

Use Azure local service with AzureClient

---

package-lock.json
package.json

upgrading the fluid package versions

Upgrade to 56

---

README.md
azure-pipelines.yml
package-lock.json
package.json

The main-azure branch is a little behind the main branch, so this change cherry-picks some relevant commits into the main-azure branch.

Cherry-pick commits from main to main-azure

---

azure-pipelines.yml
package-lock.json
package.json
src/app.js

Updating the azure-main branch to 1.0

update azure-main to 1.0

---

local.settings.json
package-lock.json
package.json

updated fluid frame work and tinylicious client versions.

updated fluid-framework and tinylicious-client versions

---

.gitignore
azure-pipelines.yml
jest.config.js
package-lock.json
package.json
test/app.test.js

The expected test report artifact was not being generated with our existing script configuration. This PR updates the scripts to ensure the artifact is generated as expected.
Also improves a code comment that I encountered while looking at the code.

ci: Publish test results when running tests in pipelines

---

package-lock.json
package.json
src/app.js
webpack.config.js

Updates FluidHelloWorld to use SharedTree rather than SharedMap.

Update to use 2.0 and SharedTree

---

package-lock.json
package.json

Update the repository's dependencies to use the latest rc: 2.0.0-rc.2.0.1.
I ran locally to test the demo still work as expected
ADO Item: https://dev.azure.com/fluidframework/internal/_workitems/edit/7639

Update FluidHelloWorld to latest rc (2.0.0-rc.2.0.1) 

---

package-lock.json
package.json
src/app.js

Update to rc3. This change uses a prerelease build. Will update to rc3 as soon as it is available and before merging.

Update to rc3

---

azure-pipelines.yml

fluid hello world broke because of the arrow app, fixed with arm service connection

Update FluidHelloWorld to Arm Arrow service connection

---

package-lock.json
package.json

The example is running against local service.
[AB#8077](https://dev.azure.com/fluidframework/internal/_workitems/edit/8077)

Update examples to rc.4.0.4 patch release

---

azure-pipelines.yml

Arrow has been upgraded to V5 in main, doing the same to everywhere that needs updating in our code base

Update Arrow to V5 in FluidHelloWorld

---

package-lock.json
package.json

bump to 2.1.0

---

package-lock.json
package.json

bump to 2.2.0

---

package-lock.json
package.json

Trying to address a few dependabot alerts at once.

Run npm update and also update specified webpack

---

package-lock.json
package.json

bump to 2.4.0

---

azure-pipelines.yml

We're moving our agent pools to a new region. This updates the pool for this repo.
AB#23299

Use new pool

---

CODE_OF_CONDUCT.md
SECURITY.md
package-lock.json
package.json

Formatting differences seem to be the result of a change in list formatting policy for Markdown.

build: Update dev dependency on `prettier` and update documentation formatting

---

package-lock.json
package.json

Specifically:
- `puppeteer`
- `start-server-and-test`

build: Update dependencies

---

package-lock.json
package.json

Manual updates since dependabot's PRs are still refusing to run required PR checks.

Bump  the fluid-framework-dependencies group and puppeteer 
